Job "solvated (solvent: water)" (8596950551) encountered an exception on step 0:
Traceback (most recent call last):
  File "/Users/hanzhang/Desktop/auto_cgui-master/CGUIBrowserProcess.py", line 198, in run
    self.eval(poststep)
  File "/Users/hanzhang/Desktop/auto_cgui-master/CGUIBrowserProcess.py", line 107, in eval
    return eval(expr)
  File "<string>", line 1, in <module>
  File "/Users/hanzhang/Desktop/auto_cgui-master/CGUIBrowserProcess.py", line 53, in click
    self.wait_text(wait)
  File "/Users/hanzhang/Desktop/auto_cgui-master/CGUIBrowserProcess.py", line 229, in wait_text
    while not self.browser.is_text_present(text, wait_time=1):
  File "/Users/hanzhang/opt/anaconda3/lib/python3.7/site-packages/splinter-0.13.0-py3.7.egg/splinter/driver/webdriver/__init__.py", line 410, in is_text_present
    self.driver.find_element_by_tag_name("body").text.index(text)
  File "/Users/hanzhang/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/Users/hanzhang/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/hanzhang/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/hanzhang/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (Session info: chrome=80.0.3987.163)


Job "pdbreader (solvent: water)" (-1) encountered an exception on step -1:
Traceback (most recent call last):
  File "/Users/hanzhang/Desktop/fep-coding/CGUIBrowserProcess.py", line 169, in run
    self.init_system(test_case)
  File "/Users/hanzhang/Desktop/fep-coding/MCABrowserProcess.py", line 61, in init_system
    self.components = test_case['components']
KeyError: 'components'

Job "pdbreader (solvent: water+ions)" (-1) encountered an exception on step -1:
Traceback (most recent call last):
  File "/Users/hanzhang/Desktop/fep-coding/CGUIBrowserProcess.py", line 169, in run
    self.init_system(test_case)
  File "/Users/hanzhang/Desktop/fep-coding/MCABrowserProcess.py", line 61, in init_system
    self.components = test_case['components']
KeyError: 'components'

